name: AutoBuild

on:
  push:
    tags:
      - "*"

env:
  DOTNET_SDK_VERSION: 6.0.x

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0
        with:
          submodules: recursive

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}

      - name: Verify .NET Core
        run: dotnet --info

      - name: Restore packages in preparation for ASFEnhance publishing
        run: dotnet restore ASFEnhance -p:ContinuousIntegrationBuild=true --nologo

      - name: Publish ASFEnhance on Windows
        shell: pwsh
        run: |
          $script = "./build.ps1";
          Set-Location ${{ github.workspace }};
          powershell $script;

      - name: Upload ASFEnhance-zh-Hans
        continue-on-error: true
        uses: actions/upload-artifact@v3.1.1
        with:
          name: ASFEnhance-zh-Hans
          path: dist/ASFEnhance-zh-Hans.zip

      - name: Upload ASFEnhance-en-US
        continue-on-error: true
        uses: actions/upload-artifact@v3.1.1
        with:
          name: ASFEnhance-en-US
          path: dist/ASFEnhance-en-US.zip

      - name: Upload ASFEnhance-ru-RU
        continue-on-error: true
        uses: actions/upload-artifact@v3.1.1
        with:
          name: ASFEnhance-ru-RU
          path: dist/ASFEnhance-ru-RU.zip

  release:
    needs: publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0

      - name: Download ASFEnhance-zh-Hans artifact from windows-latest
        uses: actions/download-artifact@v3.0.1
        with:
          name: ASFEnhance-zh-Hans
          path: out

      - name: Download ASFEnhance-en-US artifact from windows-latest
        uses: actions/download-artifact@v3.0.1
        with:
          name: ASFEnhance-en-US
          path: out

      - name: Download ASFEnhance-ru-RU artifact from windows-latest
        uses: actions/download-artifact@v3.0.1
        with:
          name: ASFEnhance-ru-RU
          path: out

      - name: Create ASFEnhance GitHub release
        id: github_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ASFEnhance ${{ github.ref }}
          body: |
            [![ASFEnhance Release](https://img.shields.io/badge/ASFEnhance-${{ github.ref }}-brightgreen)](https://github.com/chr233/ASFEnhance/releases/tag/${{ github.ref }})
            
            使用命令 `AU` 自动更新插件
            Use command `AU` to update this plugin

            release created bt github actions
          prerelease: true

      - name: Upload ASFEnhance-zh-Hans to GitHub release
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.github_release.outputs.upload_url }}
          asset_path: out/ASFEnhance-zh-Hans.zip
          asset_name: ASFEnhance-zh-Hans.zip
          asset_content_type: application/zip

      - name: Upload ASFEnhance-zh-Hans to GitHub release
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.github_release.outputs.upload_url }}
          asset_path: out/ASFEnhance-en-US.zip
          asset_name: ASFEnhance-en-US.zip
          asset_content_type: application/zip

      - name: Upload ASFEnhance-ru-RU to GitHub release
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.github_release.outputs.upload_url }}
          asset_path: out/ASFEnhance-ru-RU.zip
          asset_name: ASFEnhance-ru-RU.zip
          asset_content_type: application/zip
